### ISSUE TITLE
PERSISTENCE_MAP should not include band/subinstrument.

### ISSUE THREAD

**Issue by hugobuddel** [AstarVienna/METIS_Simulations#94]
The `PERSISTENCE_MAP` as designed does not include a band/subinstrument, so no `LM`, `N`, or `IFU`.

The idea was that the `PERSISTENCE_MAP` is always for a single exposure, unlike e.g. a `MASTER_DARK`, that is, every `MASTER_DARK_2RG` can in theory be applied to every 2RG observation. This is not true for the `PERSISTENCE_MAP`, so it is not necessary/useful to add that information to the tag.

Now maybe that decision should be updated; I'm not sure. If we change it, the addition should be `2RG`, `N`, or `IFU`, not `LM` or `N`, because the persistence is not a function of the band, but of the detector. But I suggest to do that change collectively and after this release.

@JenniferKarr could you therefore for now remove the `PERSISTENCE_MAP_LM` etc and add the `PERSISTENCE_MAP`? Then we can discuss later whether to change it.

Note that the 'check against the DRLD' scripts would have picked up this discrepancy, so I encourage you tot use those. (But they are now broken due to #84 .)

**Comment by JenniferKarr** [comment]
I've updated the repository in METIS_Pipeline_Test_Data. This repository won't change, and the generation the Persistance map was done on already produced data.

**Comment by hugobuddel** [comment]
Oh sorry @JenniferKarr , I thought that those files were created in this repository, my bad, I'll close this
